CREATE DATABASE IF NOT EXISTS db;
CREATE table IF NOT EXISTS  db.users(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(80) NOT NULL
);

CREATE table IF NOT EXISTS db.players(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    age INTEGER NOT NULL,
    position VARCHAR(30) NOT NULL
);

CREATE table IF NOT EXISTS db.userteams(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    teamname VARCHAR(50) NOT NULL,
    user_id INTEGER NOT NULL,
    player1 VARCHAR(50) NOT NULL,
    player2 VARCHAR(50) NOT NULL,
    player3 VARCHAR(50) NOT NULL,
    player4 VARCHAR(50) NOT NULL,
    player5 VARCHAR(50) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` VALUES (1,'admin','admin');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;